# Deploy example data
name: Example Data

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "example-data"
  cancel-in-progress: false

jobs:
  deploy-example-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Prepare data
      - name: Prepare Data
        run: |
          cp -r example_data _temp

      # Configure Git, Important for actions to commit
      - name: Configure Git
        run: |
          git config --global user.email "jan.oboril@gmail.com"
          git config --global user.name "Jan Oboril"

      # Check if branch exists and create or clean it
      - name: Prepare Branch
        run: |
          git checkout -b example-data
          git pull origin example-data --rebase || true


      # Add the compressed data file
      - name: Add Data and Commit
        run: |
          git rm -rf .
          mv _temp/* .
          ls -la
          rm -rf _temp
          git add README.md calibration/* reaction_ba_ome_nme2/*
          git commit -m "Added example data" || true

      # Push the branch to remote
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: example-data